apiVersion: v1
kind: ConfigMap
metadata:
  name: nvme-storage-configurator
  namespace: nvme-storage-config
data:
  configure.sh: |
    #!/usr/bin/env bash

    if [ -f /host-etc-systemd-dir/nvme-init-done ]; then
      echo 'NVMe init already done'
      exit 0
    fi

    for i in nvme-storage-format.service var-home-nvme.mount nvme-storage-dirs.service var-lib-kubelet.mount var-lib-containers.mount; do
      cp -f "/scripts/$i" "/host-etc-systemd-dir/$i"
      chmod 0644 "/host-etc-systemd-dir/$i"
    done

    nsenter -t 1 -m -u -i -n -p -- systemctl daemon-reload
    ###nsenter -t 1 -m -u -i -n -p -- systemctl enable nvme-storage-format.service var-home-nvme.mount nvme-storage-dirs.service var-lib-kubelet.mount var-lib-containers.mount
    touch /host-etc-systemd-dir/nvme-init-done
    ###nsenter -t 1 -m -u -i -n -p -- systemctl reboot

  nvme-storage-format.service: |
    [Unit]
    Description=Format NVMe drive if needed
    Before=var-home-nvme.mount
    After=sysinit.target

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    Restart=no
    ExecStart=/bin/bash -xc "lsblk -no FSTYPE /dev/nvme0n1 | grep -qE '\S' && echo 'Already formated' || mkfs -t xfs /dev/nvme1n1"

  var-home-nvme.mount: |
    [Unit]
    Description=Mount NVMe drive
    After=nvme-storage-format.service
    BindsTo=nvme-storage-format.service
    Before=local-fs.target

    [Mount]
    What=/dev/nvme1n1
    Where=/var/home/nvme
    Type=xfs
    DirectoryMode=0755

  nvme-storage-dirs.service: |
    [Unit]
    Description=Create directories on NVMe drive if needed
    After=var-home-nvme.mount
    BindsTo=var-home-nvme.mount
    Before=var-lib-kubelet.mount var-lib-containers.mount

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    Restart=no
    ExecStart=/bin/bash -xc "mkdir -p /var/home/nvme/var-lib-kubelet /var/home/nvme/var-lib-containers"

  var-lib-kubelet.mount: |
    [Unit]
    Description=Bind mount kubelet directory on NVMe drive
    Before=local-fs.target kubelet-dependencies.target
    After=nvme-storage-dirs.service
    BindsTo=nvme-storage-dirs.service

    [Mount]
    Where=/var/lib/kubelet
    What=/var/home/nvme/var-lib-kubelet
    Options=bind
    DirectoryMode=0755

    [Install]
    RequiredBy=kubelet-dependencies.target
  var-lib-containers.mount: |
    [Unit]
    Description=Bind mount containers directory on NVMe drive
    Before=local-fs.target kubelet-dependencies.target
    After=nvme-storage-dirs.service
    BindsTo=nvme-storage-dirs.service

    [Mount]
    Where=/var/lib/containers
    What=/var/home/nvme/var-lib-containers
    Options=bind
    DirectoryMode=0755

    [Install]
    RequiredBy=kubelet-dependencies.target
