apiVersion: v1
kind: ConfigMap
metadata:
  name: nvme-storage-configurator
  namespace: kube-system
data:
  configure.sh: |
    #!/usr/bin/env bash

    # Enable debugging
    set -x

    if [ -f /host-etc-systemd-dir/nvme-init-done ]; then
        echo 'NVMe init already done'
        exit 0
    fi

    cp -f /scripts/configuration.sh /host-usr-local-bin/configuration.sh
    chmod 0755 /host-usr-local-bin/configuration.sh

    cp -f /scripts/nvme-storage.service /host-etc-systemd-dir/nvme-storage.service
    chmod 0644 /host-etc-systemd-dir/nvme-storage.service

    nsenter -t 1 -m -u -i -n -p -- systemctl daemon-reload
    nsenter -t 1 -m -u -i -n -p -- systemctl enable --now nvme-storage.service
    nsenter -t 1 -m -u -i -n -p -- sleep 10
    nsenter -t 1 -m -u -i -n -p -- restorecon -R -v -F /var/lib/containers /var/lib/kubelet/pods
    touch /host-etc-systemd-dir/nvme-init-done
    nsenter -t 1 -m -u -i -n -p -- systemctl restart kubelet.service

    if [ $? -eq 0 ]; then
        echo "The last command was successful. Exiting gracefully."
        exit 0
    else
        echo "The last command failed. Exiting with an error."
        exit 1
    fi

  configuration.sh: |
    #!/usr/bin/env bash

    set -x

    DEVICE="/dev/nvme1n1"
    echo "Going to use device $DEVICE"

    export MOUNT_POINT="/home/nvme"
    export TARGET_DIR="/var/lib"
    export FSTYPE="xfs"

    mkdir -p ${MOUNT_POINT}

    if lsblk -no FSTYPE "$DEVICE" | grep -qE '\S'; then
        echo "File system already exists on $DEVICE."
    else
        echo "No file system found on $DEVICE. Creating XFS filesystem..."
        mkfs -t "$FSTYPE" "$DEVICE"
    fi

    if ! grep -q "$DEVICE $MOUNT_POINT" /etc/fstab; then
        echo "$DEVICE $MOUNT_POINT $FSTYPE defaults 0 0" >> /etc/fstab
    fi

    mount -a

    mount

    mkdir -p ${MOUNT_POINT}/var-lib-kubelet
    mount --bind /var/home/nvme/var-lib-kubelet ${TARGET_DIR}/kubelet/pods

    mkdir -p ${MOUNT_POINT}/var-lib-containers
    mount --bind /var/home/nvme/var-lib-containers ${TARGET_DIR}/containers

    if [ $? -ne 0 ]; then
        echo "Mount Failed"
        mkdir -p /home/nvme/var-lib-kubelet /home/nvme/var-lib-containers
        mount -a
    fi

    systemctl daemon-reload

    echo "Filesystem setup and mounting complete."

  nvme-storage.service: |
    [Unit]
    Description=Custom Service for NVMe Storage
    DefaultDependencies=no
    Before=kubelet.service
    After=sysinit.target 

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    ExecStart=/usr/local/bin/configuration.sh
